"""add cart, activity, collaborative reecommender models

Revision ID: 1758b79f3c40
Revises: 25733d57af56
Create Date: 2025-09-25 19:52:08.539155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1758b79f3c40'
down_revision: Union[str, Sequence[str], None] = '25733d57af56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
